### ISSUE TITLE
There's no Eboot File

### ISSUE THREAD

**Issue by ZenoPopo** [Mars873/prboom#1]
The Eboot file is nowhere to be found

**Comment by Mars873** [comment]
Oh, I kind of abandoned the port for a while, and some of the controls are missing, but I will try to upload compiled version soon as well as try to finish the port.

**Comment by ZenoPopo** [comment]
I can help you with testing it if you want.

**Comment by ZenoPopo** [comment]
any news?

**Comment by ZenoPopo** [comment]
not at all?

**Comment by Mars873** [comment]
I created the first release, report any issues or enhancements and I will try to work on it ASAP.
